title: Advanced Networking
description: ELEC-E7321

permalink: pretty  # default, no .html extension, URLs end with /

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default